#!/usr/bin/env bash

### Main Variables ###

new_loc="/mnt/unionfs/bif"
local="/mnt/local/bif"
plex_dir="/opt/plex/Library/Application Support/Plex Media Server/Media/"

### End Variables ###

### Start Functions ###

arrayRead() {
readarray -t bifArray < <(fd -e bif index-sd "$plex_dir")
}

moveCreate() {
for index in "${bif_array[@]}"; do
  gai=$(echo $index | grep -oP '(?<=/localhost/).*(?=/Contents/)')
    echo "$(date "+%d.%m.%Y %T") INFO: Creating directory $local/Media/localhost/$gai/Contents/Indexes/"
      mkdir -p "$local/Media/localhost/$gai/Contents/Indexes/"
    echo "$(date "+%d.%m.%Y %T") INFO: Moving file from $index to $local/Media/localhost/$gai/Contents/Indexes/"
      mv "$index" "$local/Media/localhost/$gai/Contents/Indexes/"
done
}

uploadFile() {
echo "$(date "+%d.%m.%Y %T") INFO: Cloudplow is now uploading these files."
  cloudplow upload
echo "$(date "+%d.%m.%Y %T") INFO: Sleeping for 1 minute to let the mount polling catch up."
  sleep 1m
}

symlinkCreate() {
for index in "${bifAarray[@]}"; do
  gai=$(echo $index | grep -oP '(?<=/localhost/).*(?=/Contents/)')
    echo "$(date "+%d.%m.%Y %T") INFO: Creating symlink from $new_loc/Media/localhost/$gai/Contents/Indexes/index-sd.bif $index"
      ln -s "$new_loc/Media/localhost/$gai/Contents/Indexes/index-sd.bif" "$index"
done
}

### End Functions ###

### Run Functions ###

arrayRead
moveCreate
uploadFile
symlinkCreate