#!/usr/bin/env bash

# Exit codes
# 1 = Script cancelled due to no files.

### Main Variables ###


### End Variables ###

### Start Functions ###

echo "$(date "+%d.%m.%Y %T") INFO: *** Starting script. ***

arrayRead() {
readarray -t bifArray < <(fd -e bif index-sd "$dir_plex")
}

checkExist() {
if [ ${#bifArray[@]} -eq 0 ]; then
  echo "$(date "+%d.%m.%Y %T") INFO: There are ${#bif_array[@]} index-sd.bif files currently. Exiting script."
  exit 1
else
  echo "$(date "+%d.%m.%Y %T") INFO: There are currently ${#bif_array[@]} index-sd.bif files. Moving to next step."
fi
}

moveCreate() {
for index in "${bifArray[@]}"; do
  gai=$(echo $index | grep -oP '(?<=/localhost/).*(?=/Contents/)')
    echo "$(date "+%d.%m.%Y %T") INFO: Creating directory $dir_local/Media/localhost/$gai/Contents/Indexes/"
      mkdir -p "$dir_local/Media/localhost/$gai/Contents/Indexes/"
    echo "$(date "+%d.%m.%Y %T") INFO: Moving file from $index to $dir_local/Media/localhost/$gai/Contents/Indexes/"
      mv "$index" "$dir_local/Media/localhost/$gai/Contents/Indexes/"
done
}

uploadFile() {
echo "$(date "+%d.%m.%Y %T") INFO: Cloudplow is now uploading these files."
  cloudplow upload
echo "$(date "+%d.%m.%Y %T") INFO: Sleeping for 1 minute to let the mount polling catch up."
  sleep 1m
}

symlinkCreate() {
for index in "${bifAarray[@]}"; do
  gai=$(echo $index | grep -oP '(?<=/localhost/).*(?=/Contents/)')
    echo "$(date "+%d.%m.%Y %T") INFO: Creating symlink from $dir_newloc/Media/localhost/$gai/Contents/Indexes/index-sd.bif to $index."
      ln -s "$dir_newloc/Media/localhost/$gai/Contents/Indexes/index-sd.bif" "$index"
done
}

### End Functions ###

### Run Functions ###

arrayRead
checkExist
moveCreate
uploadFile
symlinkCreate