#!/usr/bin/env bash

#Detect the platform.

osDetect() {
OS="`uname`"
case $OS in
  Linux)
    OS='linux'
    ;;
  *)
    echo 'Download the proper release from https://github.com/sharkdp/fd/releases/latest'
    exit 2
    ;;
esac

OS_type="`uname -m`"
case $OS_type in
  x86_64|amd64)
    OS_type='amd64'
    ;;
  *)
    echo 'Download the proper release from https://github.com/sharkdp/fd/releases/latest'
    exit 2
    ;;
esac
}

#Detect if fd is installed.

fdDetect() {
if [[ -x "/usr/bin/fd" ]]; then
  echo "You already have fd installed."
else
  FDVERS=`fd -V`
   export VERSION=$(curl -s "https://github.com/sharkdp/fd/releases/latest" | grep -oP '(?<=tag/v).*' | cut -d'"' -f1)
   curl -L https://github.com/sharkdp/fd/releases/download/v"$VERSION"/fd_"$VERSION"_amd64.deb
   sudo dpkg -i fd_"$VERSION"_amd64.deb
   echo "$FDVERS is now installed."
fi
}


Detect if cloudplow is installed.

cloudplowDetect() {
if [[ -d "/opt/cloudplow" ]]; then
  echo "Cloudplow is already installed."
else
  echo "Cloudplow is necessary for bif_upload. You can find cloudplow here: https://github.com/l3uddz/cloudplow#installation" 
fi
}

osDetect
fdDetect
cloudplowDetect