#!/usr/bin/env bash

# Exit codes
# 1 = Script cancelled due to no files.
# 2 = Program no tinstalled.

#+++Main Variables+++#

source stdlib
cf="config.yml"
st="--stripComments"

#---End Variables---#

#+++Start Functions+++#

# Detect if fd is installed.
fdDetect() {
cmd_fd=$(curl -sL "https://api.github.com/repos/sharkdp/fd/releases/latest" | grep "fd_.*_amd64" | grep "browser_download_url" | cut -d'"' -f4)
fd_ver=$(curl -sL "https://api.github.com/repos/sharkdp/fd/releases/latest" | grep "fd_.*_amd64" | grep "browser_download_url" | cut -d'/' -f8 | cut -d'v' -f2)
if [[ ! -x "/usr/bin/fd" ]]; then
  log_info "Installing fd as it is needed for this script."
    curl -LO "$cmd_fd"
    sudo dpkg -i fd_"$fd_ver"_amd64.deb
    rm -rf fd_"$fd_ver"_amd64.deb
  log_info "$(fd -V) is now installed."
fi

if [[ "$(fd -V)" != "$fd_ver" ]]; then
  log_info "fd is already at the current version."
else
  log_info "Updating $(fd-V)" to "$fd_ver".
    sudo dpkg -r fd
    curl -LO "$cmd_fd"
    sudo dpkg -i fd_"$fd_ver"_amd64.deb
    rm -rf fd_"$fd_ver"_amd64.deb
  log_info "$(fd -V) is updated."
fi
}

# Detect if yyq is installed
yyqDetect() {
cmd_yyq=$(curl -sL "https://api.github.com/repos/mikefarah/yq/releases/latest" | grep "yq_linux_amd64" | grep "browser_download_url" | cut -d'"' -f4)
yyq_ver=$(curl -sL "https://api.github.com/repos/mikefarah/yq/releases/latest" | grep "yq_linux_amd64" | grep "browser_download_url" | cut -d'/' -f8)
if [[ ! -x "/usr/local/bin/yyq" ]]; then
  log_info "Installing yyq as it is needed for this script."
    sudo curl -LO "$cmd_yyq"
    sudo mv yq_linux_amd64 "/usr/local/bin/yyq"
    sudo chmod 775 "/usr/local/bin/yyq"
    sudo chown root:root "/usr/local/bin/yyq"
  log_info "$(yyq --version) is now installed."
fi

if [[ "$(yyq --version)" != "$yyq_ver" ]]; then
  log_info "yyq is already at the current version."
else
  log_info "Updating $(yyq --version) to $yyq_ver."
    sudo rm -rf "usr/local/bin/yyq"
    sudo curl -LO "$cmd_yyq"
    sudo mv yq_linux_amd64 "/usr/local/bin/yyq"
    sudo chmod 775 "/usr/local/bin/yyq"
    sudo chown root:root "/usr/local/bin/yyq"
  log_info "$(yyq --version) is now updated."
fi
}

# Detect if cloudplow is installed.
cloudplowDetect() {
if [[ ! -d "$(yyq r $cf $st dir.cloudplow)" ]]; then
  log_error "Cloudplow is necessary for symmeta. You can find the release here: https://github.com/l3uddz/cloudplow#installation"
  exit 2
fi
}

arrayRead() {
readarray -t bifArray < <(fd -e bif index-sd "$(yyq r $cf $st dir.plex)")
}

rcloneCheckFolder() {
if [[ -d "$(yyq r $cf $st dir.newloc)" ]]; then
  temp="$(yyq r $cf $st rclone.remote)"
  log_info "Your rclone bif folder exists under ${temp%:*}/bif = $(yyq r $cf $st dir.newloc). Moving to next step."
else
  log_warn "Creating rclone bif folder under ${temp%:*}/bif = $(yyq r $cf $st dir.newloc). Moving to next step"
  rclone mkdir "$(yyq r $cf $st rclone.remote):bif"
fi

if [[ -d "$(yyq r $cf $st dir.local)" ]]; then
  temp="$(yyq r $cf $st dir.local)"
  log_info "Your local bif folder exists under $(yyq r $cf $st dir.local). Moving to next step."
else
  log_warn "Creating local bif folder under $(yyq r $cf $st dir.local). Moving to next step."
  mkdir -p "$(yyq r $cf $st dir.local)"
fi
}

checkExist() {
if [[ ${#bifArray[@]} -eq 0 ]]; then
  log_info "There are ${#bifArray[@]} index-sd.bif files currently. Exiting script."
  exit 1
else
  log_info "There are currently ${#bifArray[@]} index-sd.bif files. Moving to next step."
fi
}

moveCreate() {
for index in "${bifArray[@]}"; do
  gai=$(echo "$index" | grep -oP '(?<=/localhost/).*(?=/Contents/)')
    log_info "Creating directory $(yyq r $cf dir.local)/Media/localhost/$gai/Contents/Indexes/"
      mkdir -p "$(yyq r $cf dir.local)/Media/localhost/$gai/Contents/Indexes/"
    log_info "Moving file from $index to $(yyq r $cf dir.local)/Media/localhost/$gai/Contents/Indexes/"
      mv "$index" "$(yyq r $cf dir.local)/Media/localhost/$gai/Contents/Indexes/"
done
}

uploadFile() {
log_info "Cloudplow is now uploading these files."
  cloudplow upload
log_info "Sleeping for 1 minute to let the mount polling catch up."
  sleep 1m
}

symlinkCreate() {
for index in "${bifArray[@]}"; do
  gai=$(echo "$index" | grep -oP '(?<=/localhost/).*(?=/Contents/)')
    log_info "Creating symlink from $(yyq r $cf dir.newloc)/Media/localhost/$gai/Contents/Indexes/index-sd.bif to $index."
      ln -s "$(yyq r $cf dir.newloc)/Media/localhost/$gai/Contents/Indexes/index-sd.bif" "$index"
done
}

#---End Functions---#

#+++Run Script+++#

fdDetect
yyqDetect
cloudplowDetect
log_info "*** [Starting script.] ***"
arrayRead
rcloneCheckFolder
checkExist
moveCreate
uploadFile
symlinkCreate
log_info "*** [Script is now completed.] ***"

#---End Script---#